server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: ${db_pass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:                       # this property is used to give our application one name so now in eureka
    name: User-Service               # server our application will be visible with this name.

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:                                    # this property will tell our microservice ki kis server ke
      defaultZone: http://localhost:8761/eureka     # paas jake register hona hai.

