server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: ${db_pass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

